from __future__ import annotations
from typing import Any, Callable, Dict, Optional
from equinox.core.exceptions import AuthError as AuthError

class CredentialValidationError(AuthError):
    field_name: str
    reason: str
    def __init__(self, field_name: str, reason: str) -> None: ...

AUTH_TYPES: Dict[str, str]

def _validate_credential(value: str, field_name: str) -> str: ...
def _interpolate_field(
    value: Optional[str],
    interp: Callable[[str], str],
) -> Optional[str]: ...

class AuthStrategy:
    AUTH_TYPE: str
    DISPLAY_NAME: str

    def apply(self, request: Any, headers: Dict[str, str]) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: Dict[str, Any], **kwargs: Any) -> AuthStrategy: ...
    def interpolate(self, interp: Callable[[str], str]) -> AuthStrategy: ...
    def interpolate_fields(self, interp: Callable[[str], str]) -> AuthStrategy: ...
    def get_display_summary(self) -> str: ...
    def get_preflight_warning(self) -> Optional[str]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
