#!/usr/bin/env python
"""Generate or verify the pip-tools lockfile from pyproject.toml.

Usage:
    py -3 scripts/manage_requirements_lock.py --write
    py -3 scripts/manage_requirements_lock.py --check
"""

import argparse
import difflib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "requirements-lock.txt"
PYPROJECT_PATH = ROOT / "pyproject.toml"
LOCK_TARGET_PYTHON = "3.10"


def _compile_lock(output_path: Path) -> subprocess.CompletedProcess[str]:
    command: list[str] = [
        sys.executable,
        "-m",
        "piptools",
        "compile",
        PYPROJECT_PATH.name,
        "--extra",
        "dev",
        "--pip-args",
        f"--python-version {LOCK_TARGET_PYTHON}",
        # Keep --write and --check behavior aligned even when an existing
        # requirements-lock.txt is present.
        "--upgrade",
        "--output-file",
        str(output_path),
        "--quiet",
    ]
    return subprocess.run(
        command,
        cwd=str(ROOT),
        text=True,
        capture_output=True,
        check=False,
    )


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _normalize_lock_text(content: str) -> str:
    """Normalize non-semantic path comments emitted by pip-compile.

    ``pip-compile`` writes absolute paths for ``--output-file`` in the header,
    which can differ between check-time temp generation and committed files.
    """
    normalized = re.sub(
        r"^# This file is autogenerated by pip-compile with Python .*$",
        "# This file is autogenerated by pip-compile with Python X.Y",
        content,
        flags=re.MULTILINE,
    )

    normalized = re.sub(
        r"(--output-file=')([^']*requirements-lock\.txt)(')",
        r"\1requirements-lock.txt\3",
        normalized,
    )
    normalized = re.sub(
        r"(--output-file=)(?!['\"])(\S*requirements-lock\.txt)",
        r"\1requirements-lock.txt",
        normalized,
    )

    normalized = re.sub(
        r"'[^']*pyproject\.toml'",
        "'pyproject.toml'",
        normalized,
    )
    normalized = re.sub(
        r'"[^"]*pyproject\.toml"',
        '"pyproject.toml"',
        normalized,
    )
    normalized = re.sub(
        r"\([^)]*pyproject\.toml\)",
        "(pyproject.toml)",
        normalized,
    )
    return normalized


def _print_failure(header: str, details: str) -> int:
    print(header)
    if details.strip():
        print(details.strip())
    return 1


def write_lockfile() -> int:
    result = _compile_lock(LOCK_PATH)
    if result.returncode != 0:
        return _print_failure(
            "requirements-lock generation failed:", result.stderr or result.stdout
        )

    print(f"Generated {LOCK_PATH.name} from {PYPROJECT_PATH.name}.")
    return 0


def check_lockfile() -> int:
    with tempfile.TemporaryDirectory(prefix="equinox-lock-") as temp_dir:
        candidate_path = Path(temp_dir) / "requirements-lock.txt"
        result = _compile_lock(candidate_path)
        if result.returncode != 0:
            return _print_failure(
                "requirements-lock validation failed during generation:",
                result.stderr or result.stdout,
            )

        existing = _normalize_lock_text(_read_text(LOCK_PATH))
        generated = _normalize_lock_text(_read_text(candidate_path))
        if existing == generated:
            print("requirements-lock.txt is up to date.")
            return 0

        diff = "".join(
            difflib.unified_diff(
                existing.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile="requirements-lock.txt",
                tofile="generated requirements-lock.txt",
            )
        )
        print("requirements-lock.txt is out of date. Regenerate it with:")
        print("  py -3 scripts/manage_requirements_lock.py --write")
        print(diff.strip())
        return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate or verify requirements-lock.txt")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="Regenerate requirements-lock.txt")
    group.add_argument(
        "--check", action="store_true", help="Verify requirements-lock.txt is current"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.write:
        return write_lockfile()
    return check_lockfile()


if __name__ == "__main__":
    sys.exit(main())
