"""Tests for lockfile generation and normalization helpers."""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT_PATH = Path(__file__).resolve().parents[2] / "scripts" / "manage_requirements_lock.py"


@pytest.fixture(scope="module")
def lock_script() -> object:
    spec = importlib.util.spec_from_file_location("manage_requirements_lock", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_compile_lock_targets_python_310(
    lock_script: object,
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    calls: list[list[str]] = []

    def fake_run(command, cwd=None, text=None, capture_output=None, check=None):
        calls.append(list(command))
        return subprocess.CompletedProcess(command, 0, stdout="", stderr="")

    monkeypatch.setattr(lock_script.subprocess, "run", fake_run)

    output_path = tmp_path / "requirements-lock.txt"
    result = lock_script._compile_lock(output_path)

    assert result.returncode == 0
    assert len(calls) == 1
    command = calls[0]
    assert command[:4] == [sys.executable, "-m", "piptools", "compile"]
    assert "pyproject.toml" in command
    assert str(lock_script.PYPROJECT_PATH) not in command
    assert "--pip-args" in command
    assert "--python-version 3.10" in command
    assert "--upgrade" in command


def test_normalize_lock_text_removes_environment_specific_variance(lock_script: object) -> None:
    raw = "\n".join(
        [
            "# This file is autogenerated by pip-compile with Python 3.13",
            "#    pip-compile --extra=dev --output-file='C:\\tmp\\requirements-lock.txt' 'C:\\repo\\pyproject.toml'",
            "typing-extensions==4.15.0",
            "    # via equinox (C:/repo/pyproject.toml)",
        ],
    )

    normalized = lock_script._normalize_lock_text(raw)

    assert "Python X.Y" in normalized
    # Must collapse to the same unquoted form regardless of whether
    # pip-compile happened to quote the path (Windows vs. Linux) - a quoted
    # and an unquoted echo of the same logical path are not "variance".
    assert "--output-file=requirements-lock.txt" in normalized
    assert "--output-file='requirements-lock.txt'" not in normalized
    assert "'pyproject.toml'" in normalized
    assert "(pyproject.toml)" in normalized
    assert "C:/repo/pyproject.toml" not in normalized
    assert "C:\\repo\\pyproject.toml" not in normalized


def test_normalize_lock_text_converges_regardless_of_quoting(lock_script: object) -> None:
    """A quoted (Windows) and unquoted (Linux) echo of the same command must
    normalize identically, or `--write` on one OS can never match `--check`
    on the other.
    """
    quoted = "#    pip-compile --extra=dev --output-file='requirements-lock.txt' pyproject.toml"
    unquoted = "#    pip-compile --extra=dev --output-file=requirements-lock.txt pyproject.toml"

    assert lock_script._normalize_lock_text(quoted) == lock_script._normalize_lock_text(unquoted)
